# Site Settings
title: "hubbertz Portfolio"
name: "Max Hubbertz"
description: "Meine persönliche Website mit Projekten und Blog"
url: "https://hubbertz.github.io"
baseurl: ""
repository: "hubbertz/hubbertz.github.io"

# Theme (Remote Theme für GitHub Pages)
remote_theme: "mmistakes/minimal-mistakes"

# Site Author
author:
  name: "Max Hubbertz"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Webentwickler und Designer aus Hamburg"
  location: "Hamburg, Deutschland"
  email: "kontakt@hubbertz.de"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hubbertz"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/Berlin

# Plugins (nur GitHub Pages kompatible)
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

# Reading Files
include:
  - .htaccess
  - _pages

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true